name: Selenium Java Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-java-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
      webapp:
        name: node-container
        image: node:16-slim
        ports:
          - 3000:3000
        options: >-
          --health-cmd "curl -f http://localhost:3000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        detach: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies and start server
      run: |
        npm install
        npm start &
        sleep 20  # Ensure the server has time to start

    - name: Wait for Webapp to Start
      run: |
        sleep 30  # Wait for the webapp container to be ready

    - name: Check Webapp Container Logs
      run: |
        docker ps -a
        docker logs node-container

    - name: Run Tests
      run: mvn test
      env:
        BROWSER: chrome  # Example environment variable for browser choice
